### ISSUE TITLE
App crashed during sign-up

### ISSUE THREAD

**Issue by sea-witch** [lizziesz/hitchbike#56]
I filled out the sign-up form at https://hitch-bike.herokuapp.com/#/signup. When I clicked Submit, the app just stopped. The form was still there. 

I checked the browser console and saw this error:

<img width="493" alt="screen shot 2016-09-12 at 10 18 21 am" src="https://cloud.githubusercontent.com/assets/12530451/18439210/6a974008-78d2-11e6-80bf-4ad937801820.png">

I checked the network tab, and it seems that the form wasn't submitted. The error seems to occur before the app has a chance to submit the post request.

**Comment by lizziesz** [comment]
I believe this error was due to the form not properly submitting because of missing fields on the sign up form - I added validation to the form to make required fields obvious to the user and so the form won't try to be submitted before all fields are filled, so the error shouldn't appear anymore.

**Comment by sea-witch** [comment]
Oh, that makes sense. I realize I selected anything on the "State" dropdown. When I did the signup worked.

I didn't see the validation on the form, but maybe it hasn't updated yet? Super cool app!
